---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  serviceName: "grafana"
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:5.1.3
        ports:
          - name: grafana
            containerPort: 3000
        volumeMounts:
          - name: grafana-data
            mountPath: /var/lib/grafana
          - name: grafana-datasources
            mountPath: /etc/grafana/provisioning/datasources
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 472
        fsGroup: 472
      volumes:
      - name: grafana-datasources
        configMap:
          defaultMode: 420
          name: grafana-datasources
  volumeClaimTemplates:
    - metadata:
        name: grafana-data
        labels:
          app: grafana
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 500Mi
...
