---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - alertmanager
  - kube-state-metrics
  - node-exporter
  - prometheus-adapter

resources:
  - clusterRole.yaml
  - clusterRoleBinding.yaml
  - roleBindingConfig.yaml
  - roleBindingSpecificNamespaces.yaml
  - roleConfig.yaml
  - roleSpecificNamespaces.yaml
  - prometheus.yaml
  - rules.yaml
  - serviceAccount.yaml
  - serviceMonitor.yaml
  - serviceMonitorApiserver.yaml
  - serviceMonitorCoreDNS.yaml
  - serviceMonitorKubeControllerManager.yaml
  - serviceMonitorKubelet.yaml
  - serviceMonitorKubeScheduler.yaml
  - service.yaml
...
