---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-web
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  selector:
    app: nginx
...
