---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceAccount.yaml
  - clusterRole.yaml
  - clusterRoleAggregatedMetricsReader.yaml
  - clusterRoleBinding.yaml
  - clusterRoleBindingDelegator.yaml
  - clusterRoleServerResources.yaml
  - roleBindingAuthReader.yaml
  - apiService.yaml
  - configMap.yaml
  - deployment.yaml
  - service.yaml
  - serviceMonitor.yaml
...
